name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  githubToken: # change this
    required: true
    description: 'github token for GraphQL'
runs:
  using: 'node16'
  main: 'dist/index.js'
