name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  path:
    required: true
    description: 'the path to your SSM ParameterStore'
  email:
    required: true
    description: 'Heroku email'
  token:
    required: true
    description: 'Heroku token'
  app:
    required: true
    description: 'Heroku app name'
runs:
  using: 'node16'
  main: 'dist/index.js'
